ILMP/ILMP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from ILMP_app import views
from ILMP_app.views import index, UserDeleteView, UserUpdateView, UserCreateView, UserDetailView, UserListView, EncuentrosDeleteView, EncuentrosUpdateView, EncuentrosCreateView, PerdidosUpdateView, PerdidosDeleteView, PerdidosCreateView ,MascotasDeleteView, MascotasUpdateView, MascotasCreateView, PerdidosDetailView, EncuentrosDetailView, MascotasDetailView, MascotasListView, EncuentrosListView, PerdidosListView
from django.views.generic.base import TemplateView
from ILMP_app.api import router
##Api

#from django.urls import path, include
#from django.contrib.auth.models import User
#from rest_framework import routers, serializers, viewsets


##

urlpatterns = [
    
    #Index
    #path('', index),
    path('', include(('ILMP_app.urls','ilmp'),namespace="ilmp")),

    #Admin
    path('admin/', admin.site.urls),

    #Accounts
    #path("accounts/", ("django.contrib.auth.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("register/", views.register_request, name="register"),
    #path("", TemplateView.as_view(template_name="ILMP_app/index.html"),name="index"),
    
    #Api
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ILMP/ILMP_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from ILMP_app import views
from ILMP_app.views import index, UserDeleteView, UserUpdateView, UserCreateView, UserDetailView, UserListView, EncuentrosDeleteView, EncuentrosUpdateView, EncuentrosCreateView, PerdidosUpdateView, PerdidosDeleteView, PerdidosCreateView ,MascotasDeleteView, MascotasUpdateView, MascotasCreateView, PerdidosDetailView, EncuentrosDetailView, MascotasDetailView, MascotasListView, EncuentrosListView, PerdidosListView
from django.views.generic.base import TemplateView
from ILMP_app.api import router
##Api

#from django.urls import path, include
#from django.contrib.auth.models import User
#from rest_framework import routers, serializers, viewsets


##

urlpatterns = [
    
    #Index
    #path('', index),
    path('', index),

    #Usuarios
    path('user/', UserListView.as_view(), name='user-list'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path("register/", UserCreateView.as_view(), name='user-add'),
    path('user/<int:pk>/edit/', UserUpdateView.as_view(), name='user-update'),
    path('user/<int:pk>/delete/', UserDeleteView.as_view(), name='user-delete'),

    #Mascotas
    path('mascotas/', MascotasListView.as_view(), name='mascotas-list'),
    path('mascotas/<int:pk>/', MascotasDetailView.as_view(), name='mascotas-detail'),
    path("mascotas/add/", MascotasCreateView.as_view(), name='mascotas-add'),
    path('mascotas/<int:pk>/edit/', MascotasUpdateView.as_view(), name='mascotas-update'),
    path('mascotas/<int:pk>/delete/', MascotasDeleteView.as_view(), name='mascotas-delete'),

    #Encuentros
    path('encuentros/', EncuentrosListView.as_view(), name ='encuentros-list'),
    path('encuentros/<int:pk>/', EncuentrosDetailView.as_view(), name='encuentros-detail'),
    path("encuentros/add/", EncuentrosCreateView.as_view(), name='encuentros-add'),
    path('encuentros/<int:pk>/edit/', EncuentrosUpdateView.as_view(), name='encuentros-update'),
    path('encuentros/<int:pk>/delete/', EncuentrosDeleteView.as_view(), name='encuentros-delete'),

    #Perdidos
    path('perdidos/', PerdidosListView.as_view(), name='perdidos-list'),
    path('perdidos/<int:pk>/', PerdidosDetailView.as_view(), name='perdidos-detail'),
    path("perdidos/add/", PerdidosCreateView.as_view(), name='perdidos-add'),
    path('perdidos/<int:pk>/edit/', PerdidosUpdateView.as_view(), name='perdidos-update'),
    path('perdidos/<int:pk>/delete/', PerdidosDeleteView.as_view(), name='perdidos-delete'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ILMP/ILMP_app/models.py
from multiprocessing.dummy import Manager
from django.db import models
#from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female'),
)



#Usuarios
class User(AbstractUser):
    
    #nameUsr = models.CharField(max_length=200)
    genderUsr = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    birthUsr = models.DateField(null=True)
    telUsr= models.CharField(max_length = 9)
    imgUsr = models.ImageField(null=True, blank=True, upload_to="images/")
    ubiUsr = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse('user-list', args=[self.pk])

#class Usuarios(models.Model):
#    user = models.OneToOneField(User,on_delete=models.CASCADE)
    #nameUsr = models.CharField(max_length=200)
#    passUsr = models.CharField(max_length=200)
#    ubiUsr = models.CharField(max_length=200)
#    mailUsr = models.EmailField(max_length=254)
    #phoneUsr = models.CharField(max_length=12)
    #pub_date = models.DateTimeField('date published')

#    def __str__(self):
#        return self.user.first_name

#GENDER=[("M"),("F")]
#GENDER_CHOICES = [
#    ('Male', 'Male'),
#    ('Female', 'Female'),
#]

#class Gender(models.TextChoices):
#    Man =   "MAN",("Man")
#    Woman   =   "WOMAN",("WOMAN")

#gender = models.CharField(
#    max_length = 7,
#    choices=Gender.choices,
#    default=Gender.MAN,
#)

class Mascotas(models.Model):
    namePet = models.CharField(max_length=200)
    infoPet = models.CharField(max_length=200)
    agePet = models.DateField(blank=True, null=True)
    typePet = models.CharField(max_length=200)
    imgPet = models.ImageField(null=True, blank=True, upload_to="images/")
    #imgPet = models.FileField(upload_to=None)
    #imgPet = models.ImageField(upload_to=None, height_field=None, width_field=None, max_length=100)
    genderPet = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    usrPet = models.ForeignKey("User", on_delete=models.CASCADE, null=True)
    #imgPet = models.BooleanField()
    #models.PositiveBigIntegerField()
    
    #user = models.ForeignKey(User, on_delete=models.CASCADE)
    #genderPet = models.CharField(max_length=1, choices=GENDER)

    def __str__(self):
        return self.namePet
    def get_absolute_url(self):
        return reverse('ilmp:mascotas-list')

class Perdidos(models.Model):
    infoLost = models.CharField(max_length=200)
    dateLost = models.DateTimeField(blank=True, null=True)
    petLost = models.ForeignKey("Mascotas", on_delete=models.CASCADE, null=True)
    ubiLost = models.CharField(max_length=200, blank=True)
    #imgLost = models.ForeignKey("Mascotas", on_delete=models.CASCADE, null=True)
    #ubiLost = models.CharField(max_length=200)
    #typeLost = models.ForeignKey("Mascotas", on_delete=models.CASCADE, null=True)
    #genderLost = models.ForeignKey("Usuarios", on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.infoLost
    
class Encuentros(models.Model):
    typeFind = models.CharField(max_length=200)
    imgFind = models.ImageField(null=True, blank=True, upload_to="images/")
    #genderFind = models.CharField(max_length=1, choices=GENDER)
    infoFind = models.CharField(max_length=200)
    genderFind = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    ubiFind = models.CharField(max_length=200, blank=True)
    #ubiFind  = models.CharField(max_length=200)

    def __str__(self):
        return self.typeFind

#class Area(models.Model):
#    country = models.CharField(max_length=200)
#    comunidadautonoma = models.CharField(max_length=200)
#    provincia = models.CharField(max_length=200)
#    calle = models.CharField(max_length=200)

    #def __str__(self):
        #return self.encuentros_text

ILMP/ILMP_app/forms.py
from .models import *
from django import forms
from django.contrib.auth.forms import UserCreationForm


class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        pass

#from .models import CustomUser

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','password1','password2', 'genderUsr', 'birthUsr', 'telUsr', 'imgUsr', 'ubiUsr')


class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

ILMP/ILMP_app/views.py
from django.shortcuts import render, redirect

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
#from ILMP_app.forms import ContactForm
from ILMP_app.models import User ,Mascotas, Encuentros, Perdidos
from django.urls import reverse_lazy
from .forms import NewUserForm
from django.contrib.auth import login, authenticate
from django.contrib import messages
#from django.contrib.auth.models import User
#from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import UserForm
#Página de inicio

def index(request):
    return render(request, "ILMP_app/index.html")


#Usuarios

class UserListView(ListView):
    model = User

class UserDetailView(DetailView):
    model = User

class UserCreateView(CreateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy("ilmp:user-list")

class UserUpdateView(UpdateView):
    model = User
    fields = ['genderUsr', 'birthUsr', 'telUsr', 'imgUsr', 'ubiUsr']
    success_url = reverse_lazy("ilmp:user-list")
    #template_name = "ILMP_app/user_update_form.html"
    template_name_sufix = '_update_form'

class UserDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy("ilmp:user-list")

#Mascotas

class MascotasListView(ListView):
    model = Mascotas

class MascotasDetailView(DetailView):
    model = Mascotas

class MascotasCreateView(CreateView):
    model = Mascotas
    fields = ['namePet', 'infoPet', 'agePet', 'typePet', 'imgPet', 'genderPet', 'usrPet']
    success_url = reverse_lazy('ilmp:mascotas-list')

class MascotasUpdateView(UpdateView):
    model = Mascotas
    fields = ['namePet', 'infoPet', 'agePet', 'typePet', 'imgPet', 'genderPet', 'usrPet']
    template_name_sufix = '_update_form'

class MascotasDeleteView(DeleteView):
    model = Mascotas
    success_url = reverse_lazy('ilmp:mascotas-list')

#Encontradas

class EncuentrosListView(ListView):
    model = Encuentros

class EncuentrosDetailView(DetailView):
    model = Encuentros

class EncuentrosCreateView(CreateView):
    model = Encuentros
    fields = ['typeFind', 'infoFind', 'genderFind', 'ubiFind']
    success_url = reverse_lazy('ilmp:encuentros-list')

class EncuentrosUpdateView(UpdateView):
    model = Encuentros
    fields = ['typeFind', 'infoFind', 'genderFind', 'ubiFind']
    template_name_sufix = '_update_form'

class EncuentrosDeleteView(DeleteView):
    model = Encuentros
    success_url = reverse_lazy('ilmp:encuentros-list')

#Buscadas

class PerdidosListView(ListView):
    model = Perdidos

class PerdidosDetailView(DetailView):
    model = Perdidos

class PerdidosCreateView(CreateView):
    model = Perdidos
    fields = ['infoLost', 'dateLost', 'petLost', 'ubiLost']
    success_url = reverse_lazy('ilmp:perdidos-list')

class PerdidosUpdateView(UpdateView):
    model = Perdidos
    fields = ['infoLost', 'dateLost', 'petLost', 'ubiLost']
    template_name_sufix = '_update_form'

class PerdidosDeleteView(DeleteView):
    model = Perdidos
    success_url = reverse_lazy('ilmp:perdidos-list')


#########---------

def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registro completado." )
			return redirect("main:home")
		messages.error(request, "Fallo en el registro, informacion invalida.")
	form = NewUserForm()
	return render (request=request, template_name="/register.html", context={"register_form":form})


#def index(request):
#    return render(request,'ILMP_app/index.html')

# Create your views here.

ILMP/ILMP_app/templates/ILMP_app/encuentros_form.html
<form enctype="multipart/form-data" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar">
</form>

ILMP/ILMP_app/templates/ILMP_app/encuentros_update_form.html
<form enctype="multipart/form-data" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Modificar">
</form>

ILMP/ILMP_app/templates/ILMP_app/mascotas_detail.html
{% block content %}

    <h2>{{ object.namePet }}</h2>

    <h3>{{ object.infoPet }}</h3>

        </br>

        <p>Género : {{ object.genderPet }}</p>
        <p>Tipo de Animal : {{ object.typePet }}</p>
        <p>Nacido el {{ object.agePet }}</p>
        </br>
        <p>Imagen : <img src="/media/{{ object.imgPet }}"></p>
        <!--<p>Imagen : <img src="{{ object.imgPet }}""></p>-->
        </br>
        <p>Dueño : {{ object.usrPet }}</p>
    
{% endblock %}

ILMP/ILMP_app/templates/ILMP_app/mascotas_form.html
<form enctype="multipart/form-data" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar">
</form>

ILMP/ILMP_app/templates/ILMP_app/mascotas_list.html
{% block content %}
    <h2>Mascotas</h2>
    <ul>
        {% for mascota in object_list %}
        <li><a href={% url 'ilmp:mascotas-detail' mascota.id %}>{{ mascota.namePet }}</a>
            <!--<li>{{ mascota.namePet }}</li> -->
            <a href="{% url 'ilmp:mascotas-update' mascota.id %}"> <button>Modificar</button></a>&nbsp;&nbsp;
            <a href="{% url 'ilmp:mascotas-delete' mascota.id %}"> <button>Eliminar</button></a>
            
        </li>
        {% endfor %}
        <p><a href="{% url 'ilmp:mascotas-add' %}"> <button>Añadir Mascota</button></a></p>
    </ul>
{% endblock %}

ILMP/ILMP_app/templates/ILMP_app/mascotas_update_form.html
<form enctype="multipart/form-data" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Modificar">
</form>

ILMP/ILMP_app/templates/ILMP_app/old_index.html
<!--{% load static %}

<link rel="stylesheet" href="{% static 'css/css.css' %}">
-->
{% load static %}




<html>

<head>
	<meta charset="UTF-8">
	<meta name="description" content="Practica maquetar página"/>
	<meta name="author" content="Luis Miguel"/>
	<meta name="viewport" content="width=device-width,initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie-edge">

	<link rel="stylesheet" type="text/css" href="{% static 'css/css.css' %}">

	<title>ILMP</title>
</head>
<body>
	<nav>

        {% if user.is_authenticated %}
            <div class="nav-item">
                Logeado como {{user.username}} 
                <a href="{% url 'logout' %}">Deslogear</a>
            </div>
        {% else %}
            <div class="nav-item">
                <a href="{% url 'login' %}">Logear</a>
            </div>
            <div class="nav-item">
                <a moz-do-not-send="true" href="user/add">Registrarse</a>
            </div>
        {% endif %}

	</nav>
	<div class="container">
		<header>
			<div class="image">
				<!--<img src="img/ss.jpg" />-->
			</div>
		</header>
		<main>
			<h1>ILMP_app - Buscador</h1>
			<div class="gifs">
				<div class="gif">
					<!--<a href="http://www.google.com" target="_blank">
						<img src="img/BodyStand1_2stand.gif"/>
					</a>-->
					<h3><a moz-do-not-send="true" href="mascotas">Mascotas</a></h3>
					<!--<h3>Mascotas</h3>-->
				</div>
			<div class="gif">
				<!--<a href="http://www.google.com" target="_blank">
					<img src="img/Bunnytest8.gif"/>
				</a>-->
					<h3><a moz-do-not-send="true" href="encuentros">Encuentros</a></h3>
					<!--<h3>Mascotas Perdidas</h3>-->
				</div>
				<div class="gif">
				<!--<a href="http://www.google.com" target="_blank">
						<img src="img/Alvarojo.gif" />
					</a>-->
					<h3><a moz-do-not-send="true" href="perdidos">Pérdidas</a></h3>
					<!--<h3>Mascotas Encontradas</h3>-->
				</div>
			</div>
		</main>

		<!--<section class="tower">
			<img src="img/Floortest.png" />
			<div>
				El pixel art o arte de píxel es una forma de arte digital, creada a través de una computadora mediante el uso de programas de edición de gráficos rasterizados, donde las imágenes son editadas al nivel del píxel. Las imágenes de la mayor parte de los antiguos videojuegos para PC, videoconsolas y muchos juegos para teléfonos móviles son consideradas obras de pixel art. Posee similitudes con el puntillismo, difiriendo principalmente en las herramientas para la creación de las imágenes: computadoras y programas en lugar de pinceles y lienzos.
			</div>
			<div>
				Este tipo de dibujos ha estado muy presente en juegos antiguos, pero también se destacan juegos actuales que siguen manteniendo este arte digital como forma de diseño como por ejemplo Minecraft, que sigue trabajando a través avatares y muebles creados en pixel art y que cuenta con marcadas reglas en cuanto a este diseño como por ejemplo los bordes negros, el pixel art isométrico, etc. o juegos de videoconsolas antiguas que no soportaban grandes gráficos. 
			</div>
			<div>
				El arte de píxel debe su origen principalmente a los videojuegos, sobre todo a juegos arcade clásicos como por ejemplo Space Invaders (1978) o Pac-Man (1980) y consolas de 8 bits como la Nintendo Entertainment System (1983) y la Sega Master System (1985). 
			</div>
		</section>-->
		<section class="charas">
			Página principal en construcción

			AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
			BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
			CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
			DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
			EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
			FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
			GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGgg
			HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
			YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYy
			JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
			KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
			LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
			MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm
			NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
			<!--<img src="img/chara0.png" />
			<img src="img/chara1.png" />
			<img src="img/chara2.png" />
			<img src="img/chara3.png" />
			<img src="img/chara4.png" />
			<img src="img/chara5.png" />
			<img src="img/chara6.png" />
			<img src="img/chara6.png" />
			<img src="img/chara6.png" />
			<img src="img/chara6.png" />-->
		</section>
	</div>
	<footer>
		<address>
			<p>Jose Leon de Carranza 4trp</p>
			<p>11011 Cádiz</p>
			<p>+34123456789</p>
		</address>
		<div>Copyright 2022 derechos reservados</div>
		<section class="social">
			<a href="http://www.twitter.com" target="_blank">
				<img src="/media/img/twittericon.png">
			</a>
			<a href="http://www.github.com" target="_blank">
				<img src="/media/img/githubicon.png">
			</a>
			<a href="http://www.facebook.com" target="_blank">
				<img src="/media/img/facebookicon.png">
				<!--
				<img src="img/facebookicon.png">
				-->
			</a>
		</section>
	</footer>
</body>
</html>


<!--
Página principal en construcción
-->
<!-- LOGEAR Y DESLOGEAR(login.html, setting, urls) -->
<!--
{% if user.is_authenticated %}
    Hola {{user.username}}
    <p><a href="{% url 'logout' %}">Deslogear</a></p>
    {% else %}
    <p>No estás logeado</p>
    <a href="{% url 'login' %}">Logear</a>
    <p> O </p>
    <a moz-do-not-send="true" href="user">Registrarse</a><br>
{% endif %}
-->
<!-- HIPERVÍNCULOS(listas) -->
<!--
</br>
Apartados:
</br>
<a moz-do-not-send="true" href="mascotas">Mascotas</a><br>
<a moz-do-not-send="true" href="encuentros">Encuentros</a><br>
<a moz-do-not-send="true" href="perdidos">Pérdidas</a><br>
-->

ILMP/ILMP_app/templates/ILMP_app/perdidos_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>¿Estás seguro de eliminar la pérdida? "{{ object }}"?</p>
    <input type="submit" value="Eliminar">
</form>

ILMP/ILMP_app/templates/ILMP_app/perdidos_detail.html
{% block content %}

<h2>{{ object.infoLost }}</h2>

</br>
    <p>Nombre : {{ object.petLost }}</p>
    <!--<p>AAAAA:{{ object.petLost.genderPet }}</p>-->
    <p>Imagen : <img src="/media/{{ object.petLost.imgPet }}"></p>
    </br>
    <p>Lugar de la pérdida : {{ object.ubiLost }}</p>

{% endblock %}

ILMP/ILMP_app/templates/ILMP_app/perdidos_list.html
{% block content %}
    <h2>Mascotas perdidas</h2>
    <ul>
        {% for perdido in object_list %}
        <li><a href={% url 'ilmp:perdidos-detail' perdido.id %}>{{ perdido.petLost }}</a>
            <!--<li>{{ perdido.petLost }}</li>-->
            <a href="{% url 'ilmp:perdidos-update' perdido.id %}"> <button>Modificar</button></a>&nbsp;&nbsp;
            <a href="{% url 'ilmp:perdidos-delete' perdido.id %}"> <button>Eliminar</button></a>
        </li>
        {% endfor %}
        <p><a href="{% url 'ilmp:perdidos-add' %}"><button>Añadir</button></a></p>
    </ul>
{% endblock %}

ILMP/ILMP_app/templates/ILMP_app/perdidos_update_form.html
<form enctype="multipart/form-data" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Modificar">
</form>

ILMP/ILMP_app/templates/ILMP_app/user_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>¿Estás seguro de eliminar el usuario? "{{ object }}"?</p>
    <input type="submit" value="Eliminar">
</form>

ILMP/ILMP_app/templates/ILMP_app/user_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Registrarse">
</form>